##### Exercise 1 : Create Vectors and Matrices Using Numpy

In [4]:
import numpy as np

A = np.array([[2, 5, 3], [4, 2, 6], [1, 8, 9]])

determinant = np.linalg.det(A)
print("Determinant of the matrix A is:", determinant)

inverse = np.linalg.inv(A)
print("\nInverse of the matrix A is:\n", inverse)

Determinant of the matrix A is: -119.99999999999997

Inverse of the matrix A is:
 [[ 0.25        0.175      -0.2       ]
 [ 0.25       -0.125       0.        ]
 [-0.25        0.09166667  0.13333333]]


##### Exercise 2 : Compute Eigenvalues and Eigenvectors

In [7]:
import numpy as np

A = np.array([[2, 5], [3, 4]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of the matrix A are:", eigenvalues)
print("\nEigenvectors of the matrix A are:\n", eigenvectors)

Eigenvalues of the matrix A are: [-1.  7.]

Eigenvectors of the matrix A are:
 [[-0.85749293 -0.70710678]
 [ 0.51449576 -0.70710678]]


##### Exercise 3 : Perform Singular Value Decomposition

In [13]:
import numpy as np

A = np.array([[2, 5, -2], [3, 4, 7], [1, 0, 6]])

U, S, VT = np.linalg.svd(A)
print("Left singular vectors (U):\n", U)
print("\nSingular values (S):\n", S)
print("\nRight singular vectors (VT):\n", VT)

# reconstruct
Sigma = np.zeros(A.shape)
np.fill_diagonal(Sigma, S)
reconstructed = U @ Sigma @ VT
print("\nReconstructed matrix A from SVD:\n", reconstructed)

Left singular vectors (U):
 [[-0.06354368  0.90741949  0.41539388]
 [-0.83444643  0.18000414 -0.52086243]
 [-0.54741333 -0.37972145  0.74575482]]

Singular values (S):
 [10.21932958  6.29007638  0.01555685]

Right singular vectors (VT):
 [[-0.31096365 -0.35770489 -0.88053894]
 [ 0.31400731  0.83577904 -0.45041404]
 [ 0.89705129 -0.41655805 -0.14757495]]

Reconstructed matrix A from SVD:
 [[ 2.00000000e+00  5.00000000e+00 -2.00000000e+00]
 [ 3.00000000e+00  4.00000000e+00  7.00000000e+00]
 [ 1.00000000e+00 -9.12134653e-16  6.00000000e+00]]
