In [1]:
import numpy as np

# buat matrix 3x3
A = np.array([[4, 7, 2],
              [3, 6, 1],
              [2, 5, 3]])

# hitung determinan dan inverse
det_A =  np.linalg.det(A)
print("Determinan A:", det_A)

if det_A != 0:
       inv_A = np.linalg.inv(A)
       print("\nInverse A:\n", inv_A)
else:
       print("\nMatrix A tidak memiliki inverse karena determinannya nol.")
       
# hitung eigenvalues dan eigenvectors
eig_values, eig_vectors = np.linalg.eig(A)
print("\nEigenvalues A:", eig_values)
print("\nEigenvectors A:\n", eig_vectors)

# lakukan pemecahan matrix / SVD
U, S, VT = np.linalg.svd(A)
print("\nU Matrix:\n", U)
print("\nSingular Values:\n", S)
print("\nVT Matrix:\n", VT)

# rekonstruksi matrix dari SVD
Sigma = np.zeros((A.shape[0], A.shape[1]))
np.fill_diagonal(Sigma, S)
A_reconstructed = np.dot(U, np.dot(Sigma, VT))
print("\nReconstructed A from SVD:\n", A_reconstructed)

Determinan A: 8.999999999999998

Inverse A:
 [[ 1.44444444 -1.22222222 -0.55555556]
 [-0.77777778  0.88888889  0.22222222]
 [ 0.33333333 -0.66666667  0.33333333]]

Eigenvalues A: [10.86785194  0.51075132  1.62139674]

Eigenvectors A:
 [[-0.68311145 -0.78720544  0.15516793]
 [-0.52523497  0.49678985 -0.31978293]
 [-0.50743174 -0.3653867   0.93469877]]

U Matrix:
 [[-0.67760269  0.22302786  0.70079467]
 [-0.54945174  0.47986249 -0.68398449]
 [-0.48883267 -0.84852258 -0.20261307]]

Singular Values:
 [12.23758082  1.75075921  0.42006889]

VT Matrix:
 [[-0.43606914 -0.85671284 -0.27547562]
 [ 0.36250203  0.11295504 -0.92511266]
 [ 0.82367226 -0.50327355  0.26130393]]

Reconstructed A from SVD:
 [[4. 7. 2.]
 [3. 6. 1.]
 [2. 5. 3.]]
