##### Exercise 1 : Generate Arrays for Basic Mathematical Operations

In [4]:
import numpy as np 

a = np.arange(1,10)
b = np.arange(11,20)
print("Array a:", a)
print("Array b:", b)
print()
print("Operations between a and b:")
print()
print("Addition: ", a + b)
print()
print("Subtraction: ", a - b)
print()
print("Multiplication: ", a * b)
print()
print("Division: ", a / b)

Array a: [1 2 3 4 5 6 7 8 9]
Array b: [11 12 13 14 15 16 17 18 19]

Operations between a and b:

Addition:  [12 14 16 18 20 22 24 26 28]

Subtraction:  [-10 -10 -10 -10 -10 -10 -10 -10 -10]

Multiplication:  [ 11  24  39  56  75  96 119 144 171]

Division:  [0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421]


##### Exercise 2 : Create a 3x3 Matrix and Perform Operation

In [9]:
import numpy as np

matrixA = np.arange(1, 10).reshape(3, 3)
matrixB = np.arange(11, 20).reshape(3, 3)
print("3x3 Matrix A:\n", matrixA, "\n")
print("3x3 Matrix B:\n", matrixB, "\n")
print("Operations between matrixA and matrixB:", "\n")
print("Matrix Addition:\n", matrixA + matrixB, "\n")
print("Matrix Subtraction:\n", matrixA - matrixB, "\n")
print("Matrix Multiplication:\n", matrixA * matrixB, "\n")
print("Matrix Division:\n", matrixA / matrixB)


3x3 Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

3x3 Matrix B:
 [[11 12 13]
 [14 15 16]
 [17 18 19]] 

Operations between matrixA and matrixB: 

Matrix Addition:
 [[12 14 16]
 [18 20 22]
 [24 26 28]] 

Matrix Subtraction:
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]] 

Matrix Multiplication:
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

Matrix Division:
 [[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


##### Additional Practice : Create a 4x4 matrix and calculate the sum of its rows and columns

In [12]:
import numpy as np

matrix = np.arange(1,17).reshape(4,4)
print("4x4 Matrix:\n", matrix, "\n")
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))

4x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

Sum of each column: [28 32 36 40]
Sum of each row: [10 26 42 58]


##### Additional Practice : Write a program to normalize an array (scale values between 0 and 1)

In [14]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)

arr_min = arr.min()
arr_max = arr.max()

normalized_arr = (arr - arr_min) / (arr_max - arr_min)
print("Normalized array:", normalized_arr)

Original array: [10 20 30 40 50]
Normalized array: [0.   0.25 0.5  0.75 1.  ]


##### Additional Practice : Generate a random array and find the minimum and maximum values

In [18]:
import numpy as np

random_array = np.random.rand(5)
print("Random Array:", random_array)
print("Minimum value:", random_array.min())
print("Maximum value:", random_array.max())

Random Array: [0.45719186 0.26737734 0.19512313 0.80008599 0.00868731]
Minimum value: 0.008687306027715835
Maximum value: 0.8000859893002757
