##### Exercise 1 : Broadcasting Operations

In [8]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
print("Matrik A : \n", arr)

# scalar broadcasting
scalar_broadcasting = arr + 3
print("Matrik Scalar Broadcasting : \n", scalar_broadcasting)

# matrix & vector
vector = np.array([1, 0, -2])
print("Matrik + Vector : \n", arr + vector)

Matrik A : 
 [[1 2 3]
 [4 5 6]]
Matrik Scalar Broadcasting : 
 [[4 5 6]
 [7 8 9]]
Matrik + Vector : 
 [[2 2 1]
 [5 5 4]]


##### Exercise 2 : Generate adn Filter a Random Dataset

In [11]:
import numpy as np

# generate random int
random_number = np.random.randint(1,20, size=(5,5))
print("Number : \n", random_number)

# filtering data
random_number[random_number > 12] = 0
print("Filtering Dataset : \n", random_number)

Number : 
 [[15 16  4  9 18]
 [17  9 15  4  9]
 [ 7  1 16 11  4]
 [ 1 10  8  4  9]
 [ 3 12 17  6 16]]
Filtering Dataset : 
 [[ 0  0  4  9  0]
 [ 0  9  0  4  9]
 [ 7  1  0 11  4]
 [ 1 10  8  4  9]
 [ 3 12  0  6  0]]


##### Additional Practice 1 : Create a 3D random array and compure statistics along specific axes

In [21]:
import numpy as np

dataset = np.random.randint(1,20, size=(2,3,3))
print("Dataset : \n", dataset)
print()
print("Shape : \n", dataset.shape)
print()

# sum - gabungan Lapisan
print("Sum - Gabungkan Lapisan : \n", np.sum(dataset, axis=0))
print()

# mean - baris
print("Mean - Baris : \n", np.mean(dataset, axis=1))
print()

# max - kolom
print("Max - Kolom : \n", np.max(dataset, axis=2))


Dataset : 
 [[[ 3  2  9]
  [18  1  6]
  [16 16  3]]

 [[13  3 12]
  [ 3 15  2]
  [10  6 18]]]

Shape : 
 (2, 3, 3)

Sum - Gabungkan Lapisan : 
 [[16  5 21]
 [21 16  8]
 [26 22 21]]

Mean - Baris : 
 [[12.33333333  6.33333333  6.        ]
 [ 8.66666667  8.         10.66666667]]

Max - Kolom : 
 [[ 9 18 16]
 [13 15 18]]


##### Additional Practice 2 : Write a program to generate a dataset of random floats and normalize the values between 0 and 1

In [23]:
import numpy as np

arr_floats = np.random.uniform(1, 100, size=(5,5))
print("Original Array : \n", arr_floats)
print()

arr_min = arr_floats.min()
arr_max = arr_floats.max()

normalization_arr = (arr_floats - arr_min) / (arr_max-arr_min)
print("Array after Normalization (0-1):\n", normalization_arr)

Original Array : 
 [[95.39717488 87.37287893 91.89789496 87.71331939 30.47422958]
 [44.18970395 85.06841046 18.47908618 23.77350127 49.13586551]
 [83.83494559  3.27743671 82.74354042 12.78403332 51.89815531]
 [60.60334134 12.41814598 43.67240149 32.73129299 29.68211547]
 [46.68121531  8.49379549 47.0188623  59.86554886 55.63486065]]

Array after Normalization (0-1):
 [[1.         0.91289276 0.96201379 0.91658839 0.29523307]
 [0.44412053 0.88787675 0.16502055 0.22249373 0.49781328]
 [0.87448695 0.         0.86263927 0.10319826 0.52779914]
 [0.62229774 0.09922639 0.43850499 0.31973448 0.28663432]
 [0.47116698 0.05662585 0.47483228 0.61428868 0.56836271]]


##### Additional Practice 3 : Implement conditonal replacement to create binary mask for values above a threshold

In [25]:
import numpy as np

data = np.random.uniform(0, 100, size=(5,5))
print("Original Data : \n", data)

# make threshold
threshold = 50

# make binary mask
mask = np.where(data > threshold, 1, 0)
print("\nBinary mask (1 jika > 50, else 0):\n", mask)


Original Data : 
 [[75.41337603 61.75382732 96.4097866  21.73262488 21.1703037 ]
 [53.97072395 87.52756433 48.0133244  96.14232587 22.37328289]
 [30.63177544 41.55285043 20.01130934 82.4424143  15.48897124]
 [45.49051784 29.00072842 41.8731778  67.62209747 98.52736317]
 [92.10706899 61.10068647  9.40347515 23.82338987 66.7981489 ]]

Binary mask (1 jika > 50, else 0):
 [[1 1 1 0 0]
 [1 1 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [1 1 0 0 1]]
