##### Exercise 1 : Create Vectors and Matrices Using Numpy

In [10]:
import numpy as np

# create vector
vector = np.array([1, 3, 5])
print("Simple Vector : ", vector)

# create matrix
# set seed 
np.random.seed(42)
matrix = np.random.randint(0, 20, size=(3,3))
print("\nSimple Matrix :\n", matrix)

Simple Vector :  [1 3 5]

Simple Matrix :
 [[ 6 19 14]
 [10  7  6]
 [18 10 10]]


##### Exercise 2 : Implement Matrix-Vector Multiplication

In [14]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
vector_a = np.array([2, 5, 7])

results = np.dot(matrix_a, vector_a)

print("Matrix A : \n", matrix_a)
print("\nVector A : \n", vector_a)
print("\nMatrix A x Vector A : \n", results)

Matrix A : 
 [[1 2 3]
 [4 5 6]]

Vector A : 
 [2 5 7]

Matrix A x Vector A : 
 [33 75]


##### Exercise 3 : Explore Special Matrices

In [16]:
# Identity Matrix
identity_matrix = np.eye(4)
print("Identity Matrix : \n", identity_matrix)

# Zero Matrix
zero_matrix = np.zeros((2,2))
print("\nZero Matrix : \n", zero_matrix)

# Diagonal Matrix
diagonal_matrix = np.diag([2,5,7])
print("\nDiagonal Matrix : \n", diagonal_matrix)


Identity Matrix : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Zero Matrix : 
 [[0. 0.]
 [0. 0.]]

Diagonal Matrix : 
 [[2 0 0]
 [0 5 0]
 [0 0 7]]


##### Additional 1 : Compute The Determinant and Inverse of 2x2 Matrix using Numpy

In [17]:
np.random.seed(42)
matrix = np.random.randint(0,20, size=(2,2))
print("Matrix :\n", matrix)

# determinant matrix
det = np.linalg.det(matrix)
print("\nDeterminant :", det)

if det != 0:
    inv = np.linalg.inv(matrix)
    print("\nInverse :\n", inv)
else:
    print("\nMatrix tidak punya inverse (determinant = 0)")

Matrix :
 [[ 6 19]
 [14 10]]

Determinant : -206.00000000000003

Inverse :
 [[-0.04854369  0.09223301]
 [ 0.06796117 -0.02912621]]


##### Additional 2 : Verify Properties of Matrix Multiplication

In [19]:
# Definisikan matriks A, B, C (ukuran 2x2)
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

C = np.array([[0, 1],
              [2, 3]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix C:\n", C)

# 1. Associative: (A*B)*C == A*(B*C)
left = np.dot(np.dot(A, B), C)
right = np.dot(A, np.dot(B, C))
print("\nAssociative Law (A*B)*C == A*(B*C):")
print("Left side:\n", left)
print("Right side:\n", right)
print("Equal?", np.allclose(left, right))

# 2. Distributive: A*(B+C) == A*B + A*C
left = np.dot(A, (B + C))
right = np.dot(A, B) + np.dot(A, C)
print("\nDistributive Law A*(B+C) == A*B + A*C:")
print("Left side:\n", left)
print("Right side:\n", right)
print("Equal?", np.allclose(left, right))

# 3. Non-Commutative: A*B != B*A (umumnya)
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nNon-Commutative A*B vs B*A:")
print("A*B:\n", AB)
print("B*A:\n", BA)
print("Equal?", np.allclose(AB, BA))


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[2 0]
 [1 2]]
Matrix C:
 [[0 1]
 [2 3]]

Associative Law (A*B)*C == A*(B*C):
Left side:
 [[ 8 16]
 [16 34]]
Right side:
 [[ 8 16]
 [16 34]]
Equal? True

Distributive Law A*(B+C) == A*B + A*C:
Left side:
 [[ 8 11]
 [18 23]]
Right side:
 [[ 8 11]
 [18 23]]
Equal? True

Non-Commutative A*B vs B*A:
A*B:
 [[ 4  4]
 [10  8]]
B*A:
 [[ 2  4]
 [ 7 10]]
Equal? False


##### Additional 3 : Create a Block Diagonal Matrix Using Numpy

In [20]:
import numpy as np
from scipy.linalg import block_diag

# dua matrix kecil
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# gabung jadi block diagonal
block_matrix = block_diag(A, B)

print("Block Diagonal Matrix:\n", block_matrix)


Block Diagonal Matrix:
 [[1 2 0 0]
 [3 4 0 0]
 [0 0 5 6]
 [0 0 7 8]]
