In [5]:
import numpy as np

A = np.array([[2, 5], [1, 3]])
B = np.array([[4, 1], [2, 6]])

print("Penjumlahan:\n", A + B)
print("\nPengurangan:\n", A - B)
print("\nPerkalian Skalar:\n", 2 * A)
print("\nPerkalian Matriks:\n", np.dot(A, B))

print("\nIdentitas Matriks:\n", np.eye(2))
print("\nZero Matriks:\n", np.zeros((2,2)))
print("\nDiagonal Matriks :\n", np.diag([7,8,9]))

Penjumlahan:
 [[6 6]
 [3 9]]

Pengurangan:
 [[-2  4]
 [-1 -3]]

Perkalian Skalar:
 [[ 4 10]
 [ 2  6]]

Perkalian Matriks:
 [[18 32]
 [10 19]]

Identitas Matriks:
 [[1. 0.]
 [0. 1.]]

Zero Matriks:
 [[0. 0.]
 [0. 0.]]

Diagonal Matriks :
 [[7 0 0]
 [0 8 0]
 [0 0 9]]


##### Coba kalikan A dengan matriks identitas. Apakah hasilnya sama?

##### Coba kalikan matriks A dengan vektor [1, 0] dan amati hasilnya.

In [8]:
# A x Matriks Indentitas
question_1 = np.dot(A, np.eye(2))
print("Hasil A x Matriks Identitas:\n", question_1)

# A x Vektor [1, 0]
question_2 = np.dot(A, np.array([1,0]))
print("\nHasil A x Vektor [1, 0]:\n", question_2)

Hasil A x Matriks Identitas:
 [[2. 5.]
 [1. 3.]]

Hasil A x Vektor [1, 0]:
 [2 1]
